FROM envoyproxy/envoy:v1.19.4
ADD ./lib/mylibrary.lua /lib/mylibrary.lua
COPY ./envoy.yaml /etc/envoy.yaml
RUN chmod go+r /etc/envoy.yaml /lib/mylibrary.lua
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy.yaml", "--service-cluster", "proxy"]
